config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", locale: /en|fr/ do

	  resources :quizzes
	  resources :lessons do 
			member do
		    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
		end
	  end
	  resources :subjects
	  devise_for :users
	  get 'quiz/restart', to: 'quizzes#restart'
	  get 'static/welcome', to: 'static#welcome'
	  get 'users/about', to: 'static#about'
	  get '/about', to: 'static#about'
	  get '/chat', to: 'static#chat'
	  get '/achievements', to: 'static#achievements'
	  get '/home', to: 'static#welcome'
	  get 'static/info', to: 'static#info'
		get '/passed', to: 'analysis#passed'
		get '/dash', to: 'static#admin_dash'
		get '/failed', to: 'analysis#failed'
		get '/usermore', to: 'static#usermore'
		get '/dash/user', to: 'static#info'
	  get 'static/landing_page', to: 'static#landing_page'
	  root 'static#landing_page'
	default_url_options :host => "www.gmail.com"
	  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ edit update destroy ]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all.where(lesson_id: current_lesson.id)
  end
	def restart
		UserLessonQuiz.where(lesson_id: current_lesson.id).delete_all
		ul = UserLesson.find_by(lesson_id: current_lesson.id)
		ul.status = "started"
		ul.save
		us = UserSubject.find_by(subject_id: current_subject.id)
		us.status = "started"
		us.save
		session[:quiz_index] = 0
		redirect_to lesson_path(id: current_lesson.id)
	end
  # GET /quizzes/1 or /quizzes/1.json
  def show
		if next_quiz == 0
    	redirect_to quizzes_path
			session[:quiz_index] = 0
			user_lesson = UserLesson.find_by(lesson_id: current_lesson.id)
			user_lesson.status = "completed"
			user_lesson.save
		else
			@quiz = Quiz.find(next_quiz)
			if @quiz == nil
				session[:quiz_index] = 0 
			else
				if UserLessonQuiz.check_presence(@quiz.id).empty?
					UserLessonQuiz.create(user_id: current_user.id, lesson_id: current_lesson.id, quiz_id: @quiz.id)
				end
			end
		end
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
	@quiz.lesson = Lesson.find(current_lesson.id)
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
		my_array = []
		my_array << @quiz.option1
		my_array << @quiz.option2
		my_array << @quiz.option3
		my_array << @quiz.option4
		
		correct_respo = my_array[@quiz.correct_response.to_i - 1]
		@quiz.correct_response_text = correct_respo
		@quiz.save
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
		my_array = []
        my_array << @quiz.option1
        my_array << @quiz.option2
        my_array << @quiz.option3
        my_array << @quiz.option4

        correct_respo = my_array[@quiz.correct_response.to_i - 1]
        @quiz.correct_response_text = correct_respo
        @quiz.save
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to lesson_url(current_lesson), notice: "Quiz was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:question, :option1, :option2, :option3, :option4, :correct_response, :lesson_id)
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
  def finished_quizzes?(les_id)
    UserLessonQuiz.where(lesson_id: les_id, completed: true, user_id: current_user.id).count == Lesson.find(les_id).quizzes.count
  end
	def quiz_number(les_id)
		UserLessonQuiz.where(lesson_id: current_lesson.id, completed: true , user_id: current_user.id).count + 1
	end
	def get_failed
		UserLessonQuiz.where(user_id: current_user.id,lesson_id: current_lesson.id, verdict: "failed").count
	end
	def get_passed
		UserLessonQuiz.where(user_id: current_user.id, lesson_id: current_lesson.id, verdict: "passed").count
	end

	def get_percentage
		(get_passed.to_f/Lesson.find(current_lesson.id).quizzes.count.to_f)*100
	end
	def get_decision
		if get_percentage < 60
			return "Not completed"
		else
			return "Completed"
		end
	end
end

app/views/quizzes/_form.html.erb
<%= simple_form_for(@quiz) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :question , label_html: {class: "font-semibold"}, input_html: {class: "block w-full border border-2 border-gray-400 mb-3", rows: 3}%>
    <%= f.input :option1 , label_html: {class: "font-semibold"}, input_html: {class: " option1 py-1 block w-2/3 border border-2 border-gray-400 "} %>
    <%= f.input :option2 , label_html: {class: "font-semibold"}, input_html: {class: "option2 py-1 block w-2/3 border border-2 border-gray-400" }%>
    <%= f.input :option3 , label_html: {class: "font-semibold"}, input_html: {class: "option3 py-1 block w-2/3 border border-2 border-gray-400" }%>
    <%= f.input :option4 , label_html: {class: "font-semibold"}, input_html: {class: "option4 py-1 block w-2/3 border border-2 border-gray-400" }%>
    <%= f.input :correct_response , :collection => ([["option1",1],["option2",2], ["option3", 3],["option4",4]]) , label_html: {class: "font-semibold"}, input_html: {class: " bg-white rounded-md block py-1 w-2/3 border border-2 border-gray-400" }, include_blank: false%>
    <%= f.association :lesson , label_html: {class: " font-semibold"}, input_html: {class: "block py-1  w-full bg-white border border-2 border-gray-400" }, include_blank: false%>
  </div>
<div class=" flex justify-between mt-5">
  <div class="form-actions">
    <%= f.button :submit , class: "bg-green-600 px-8 py-1 rounded-md font-semibold ", style: "color: #ffe; "%>
  </div>
  <div>
<% end %>

app/views/quizzes/_resultpane.html.erb
<section  class = "">
	<h1 class="uppercase font-semibold bg-gray-800 text-white">statistics </h1>
	<br>
	<p> Passed : <span class=" bg-blue-400 px-2 text-lg text-white "> <%= get_passed %> </span> </p>
	<p> Failed : <span class=" bg-red-400 px-2 text-lg text-white "> <%= get_failed %> </span> </p> 
	<p> Percentage correct : <span class=" text-lg px-2 "> <%= get_percentage %> % </span> </p>
 <p> Decision : <span class="  px-2 "> <%= get_decision %> </span> </p> 
</section>

app/views/quizzes/edit.html.erb
<section>
<h1 class="text-center mb-10 text-2xl "><%= t('quiz.edit.editing_quiz') %> </h1>

<%= render 'form', quiz: @quiz %>

<%= link_to t('quiz.edit.go_to_quiz'), @quiz %> |
<%= link_to t('general_buttons.back') , quizzes_path %>

</div>

</section>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>
<section class="w-full mt-5">
	<div class=" grid grid-cols-1 md:grid-cols-4 ">
		<div class="col-span-3">
			<div class= "flex pb-5"> 
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 "> <%= link_to '<i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>'.html_safe, lesson_path(current_lesson), style: "color: #fff;" %> </div>
		<h1 class="text-xl w-full text-center border-2 border-gray-300 "> <%= t('quiz.index.results') + ": " + current_lesson.name %></h1>
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 hidden"> <%= link_to '<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>'.html_safe, quiz_path(next_quiz), style: "color: #fff;" %> </div>
	</div>

		<% if @quizzes.empty? %>
			<p class = "block w-full text-center text-lg"> No Quiz created yet. </p>
		<% else %>
			<% @quizzes.each do |quiz| %>
				<hr >
				<div class = "" >
					<div class= "w-full"><%= quiz.question %>  </div>
					<div class="w-full grid grid-cols-4">
						<% if  get_verdict(quiz.id)== "failed" %> 
							<span class = "text-red-400 font-semibold" > <%= t('quiz.index.failed') %> </span>
						<% else %>
							<span class="text-green-400 font-semibold"><%= t('quiz.index.passed') %></span>
						<% end %>
					</div>
				</div>
				
			<% end %>
		<% end %>

	<br>
		</div>
		<div class="  text-center border-l-2 border-gray-200">
			<%= render "resultpane" %>	
		</div>
	</div>
</section>

app/views/quizzes/new.html.erb
<section class="mx-4 ">
	<h1 class="text-center font-semibold text-xl"> <%= t('quiz.new.new_quiz') %> </h1>

	<%= render 'form', quiz: @quiz %>

	<%= link_to t('general_buttons.back')  , quizzes_path, class: "font-semibold rounded-md px-8 py-1" , style: "background-color: #ff3860; color: #ffe ;" %>
	</div>
</section>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>
<section class=" mt-5 w-4/5">

<div class= "flex"> 
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 "> <%= link_to '<i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>'.html_safe, lesson_path(current_lesson), style: "color: #fff;" %> </div>
		<h1 class="text-xl w-full text-center border-2 border-gray-300 ">Quiz : <%= quiz_number(current_lesson.id).to_s + "/" + current_lesson.quizzes.count.to_s  %></h1>
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 hidden"> <%= link_to '<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>'.html_safe, quiz_path(next_quiz), style: "color: #fff;" %> </div>
	</div>
	<div class= "grid grid-cols-3  md:px-2 border bordder-2 border-gray-200 mt-3">
		    <% if current_user && current_user.admin %> 
			<%= link_to  t('quiz.show.new_quiz'), new_quiz_path,  class: "font-semibold block text-center py-1 hover:bg-green-50" , style: "color: #00d1b1 ; border: 1px solid #00d1b1" %> 
			<%= link_to t('general_buttons.edit'), edit_quiz_path(@quiz) , class: "block text-center font-semibold border border-2 border-gray-700 hover:bg-gray-100 hover:text-gray-900 "%> 
			<%= link_to t('quiz.show.delete_quiz') , quiz_path(@quiz), method: :delete, class: "block text-center font-semibold" , style: "color: #ff3860;" %>
			<% end %>
		</div>

			<% if @quiz ==  nil %>
			<p class=""> <%= t('quiz.show.no_quiz') %> </p>
			<% else %>
				<div class= "w-full mx-4 mt-10 mb-2"><%= @quiz.question %>  </div>
				<hr>
				<%= form_for :something do |f|%>
				<div class="mx-4 mt-2 flex flex-row justify-between"> 
				
					<div ><%= f.radio_button :my_option,  @quiz.option1 %>  <%= @quiz.option1 %> </div>
					<div ><%= f.radio_button :my_option,  @quiz.option2 %>  <%= @quiz.option2 %> </div>
					<div ><%= f.radio_button :my_option,  @quiz.option3 %>  <%= @quiz.option3 %> </div>
					<div ><%= f.radio_button :my_option,  @quiz.option4 %>  <%= @quiz.option4 %> </div>
				</div>
				<% end %>
			<% end %>
	<br>
	<div class=" text-right flex justify-between mx-4"> 
		<div class="flex">
			<p id="btn" class="block hidden font-semibold cursor-pointer rounded-md px-8 py-1 text-blue-600 hover:bg-blue-200"> <%= t('quiz.show.verify') %></p>
			<p class=" wrong text-lg text-red-400 hidden"> <%= t('quiz.show.false') %> </p>
        <p class="correct text-lg text-green-400 hidden"> <%= t('quiz.show.correct') %> </p>

		</div>
		<%= link_to t('lessons.show.next') , quiz_path( next_quiz), class: "hidden next-button block bg-blue-400 font-semibold rounded-md px-8 py-1 ", style: "color: white;" %> </div>
		<div class="">	
		</div>

</section>


<script >
$(document).ready(function(){
        $('input').change(function(e){
           selected_value = $('form input[type=radio]:checked').val();
			$('#btn').toggleClass("hidden",false);
		console.log("<%= escape_javascript @quiz.correct_response_text %>");
		console.log(selected_value);
            $('#btn').click(function(){
				$(this).toggleClass("hidden");
				$('.next-button').toggleClass("hidden");
            	if (selected_value ==  "<%= escape_javascript @quiz.correct_response_text %>") {
            		$('.correct').toggleClass("hidden");
					$.ajax({
						type: "GET",
						url: "/passed",
						});
            		} else {
            		$('.wrong').toggleClass("hidden");
						$.ajax({
                        type: "GET",
                        url: "/failed",
                        });
            		}
            });
        });
    });

</script>