config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", locale: /en|fr/ do

	  resources :quizzes
	  resources :lessons do 
			member do
		    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
		end
	  end
	  resources :subjects
	  devise_for :users
	  get 'quiz/restart', to: 'quizzes#restart'
	  get 'static/welcome', to: 'static#welcome'
	  get 'users/about', to: 'static#about'
	  get '/about', to: 'static#about'
	  get '/chat', to: 'static#chat'
	  get '/achievements', to: 'static#achievements'
	  get '/home', to: 'static#welcome'
	  get 'static/info', to: 'static#info'
		get '/passed', to: 'analysis#passed'
		get '/dash', to: 'static#admin_dash'
		get '/failed', to: 'analysis#failed'
		get '/usermore', to: 'static#usermore'
		get '/dash/user', to: 'static#info'
	  get 'static/landing_page', to: 'static#landing_page'
	  root 'static#landing_page'
	default_url_options :host => "www.gmail.com"
	  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
	has_many :quizzes, dependent: :delete_all
	has_one_attached :lesson_video, dependent: :destroy
	has_many_attached :lesson_pictures, dependent: :destroy
	has_many :user_lesson_quizzes, dependent: :destroy
	has_many :user_lessons, dependent: :destroy
	has_rich_text :lesson_notes
#validations


	scope :unquizzed, -> { where( :quizzes_count => 0) }	
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all.where(subject_id: current_subject.id).with_rich_text_lesson_notes
  end

  # GET /lessons/1 or /lessons/1.json
  def show
  @data = "hello hillman"
		UserLesson.create(user_id: current_user.id, lesson_id: params[:id], status: "started") if UserLesson.find_by(lesson_id: params[:id]) == nil
		UserSubject.create(user_id: current_user.id, subject_id: current_subject.id, status: "started") if UserSubject.find_by(subject_id: current_subject.id) == nil
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
	@lesson.subject = Subject.find(current_subject.id )
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
	Activity.create(name: "Created lesson", description: "You just created the lesson : " + @lesson.name )
        format.html { redirect_to static_welcome_url , notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
	name= @lesson.name
    @lesson.destroy
    respond_to do |format|
	Activity.create(name: "Deleted lesson", description: "You just deleted  the lesson : " + name )
      format.html { redirect_to static_welcome_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

	def delete_image
		image = ActiveStorage::Attachment.find(params[:image_id])
		if current_user == image.record
			image.purge
			redirect_back(fallback_location: request.referer)
		else
			redirect_to root_url, notice: "Only the administrator of this site can delete pictures"
		end
	end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params 
      params.require(:lesson).permit(:name, :subject_id , :lesson_notes, :lesson_video, lesson_pictures: [])
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper

	def lesson_status(les_id)
    item = UserLesson.find_by(lesson_id: les_id)
    if item != nil
      return(item.status)
    else
      return("")
    end
  end

	def lesson_completion_percent(les_id)
    if UserLessonQuiz.where(completed: true).joins(:lesson).where("lessons.id =?",les_id).empty?
      return(0)
    else
      return (UserLessonQuiz.where(completed: true).joins(:lesson).where("lessons.id =?",les_id).count.to_f/Lesson.find(les_id).quizzes.count.to_f)*100
    end
  end

  def lesson_status_colour(les_id)
    if lesson_completion_percent(les_id) < 50
      return("red-400")
    elsif lesson_completion_percent(les_id) >= 50 && lesson_completion_percent(les_id) < 100
      return("yellow-300")
    else
      return("green-500")
    end
  end

 
end

app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>


<div class="form-inputs mb-4 ">
    <%= f.input :name , label_html: {class: " font-bold"}, input_html: {class: "border border-2 border-gray-300 rounded-sm" } %>
    
    <div class="mt-2">
		<% if @lesson.lesson_video.attached? %>
			<div style="width: 400px; height: 200px">
				<%= video_tag(url_for(@lesson.lesson_video), style: "width: 100%; height: auto;") %>
			</div>
		<% end %>
         <p class="font-bold text-lg mb-2"> Lesson video :  </p>
    	<div class =" border border-2 border-gray-200 px-1 py-1"> <%= f.file_field :lesson_video , label_html: {class: " font-bold"}, input_html: {class: "border border-2 border-gray-300 rounded-sm" }  %> </div>
     </div>
<br >
	<div class="">
		<%= f.rich_text_area :lesson_notes , label_html: {class: " font-bold" }, input_html: {class: "border border-2 border-gray-300 rounded-sm w-full" , rows: 6} %>
	</div>

     <div class="mt-2">
     <p class="font-bold text-lg mb-2"> Lesson pictures :  </p>
     <div class =" border border-2 border-gray-200 px-1 py-1"><%= f.file_field :lesson_pictures, multiple: true , label_html: {class: " font-bold"}, input_html: {class: "border border-2 border-gray-300 rounded-sm" }  , hint: "Select many" %> </div>
     </div>
    
	<%= f.association :subject, label_method: :name, value_method: :id, priority: [@sub_name.to_s],include_blank: false, input_html: { class: "border border-2 border-gray-300 rounded-sm w-full bg-white px-4 py-2"} , label_html: {class: "font-bold"}%>	 
 </div>

  <div class="form-actions">
    <%= f.submit t('lesson.new.submit') ,class: "py-1 px-4 rounded-md bg-blue-400 text-white font-semibold text-md "%>
  </div>

   

<% end %>

app/views/lessons/edit.html.erb
<h1 class="text-center mb-5 text-2xl "><%= t('lesson.edit.editing_lesson') %></h1>
<div class= "flex justify-between">
	<%= link_to t('general_buttons.back') , lessons_path, class: "block border-2 border-red-400 px-8 py-1" %>
 <%= link_to t('lessons.show.delete_lesson'), lesson_path(@lesson), method: :delete, class: " block px-8 py-1 border-2 border-gray-300" %>
 <%= link_to t('quiz.show.new_quiz'), new_quiz_path(@lesson.id) ,class: "block bg-white border-2 border-blue-400 px-8 py-1"%>  </div>
<%= render 'form', lesson: @lesson %>

app/views/lessons/index.html.erb
<p id="notice" class="block w-full  font-bold text-lg py-2 text-center "><%= notice %></p>
<section class="">
	<div class="flex">
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 "> <%= link_to '<i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>'.html_safe, static_welcome_path, style: "color: #fff;" %> </div>
		<h1 class="text-center text-xl font bold border-2 border-gray-300 w-4/5 "> <%= t('lesson.index.all_lessons') %></h1>
	</div>
	<div class=" block  mt-4 mx-10">
<!-- loop through all the subjects and display them -->
		<% if @lessons.empty? %>
			<p> No lessons created for this subject yet </p>
		<% else %>
    	<% @lessons.each do |lesson| %>
				<div class=" w-4/5 ">
    			<div class=" w-full  my-2 grid grid-cols-1 md:grid-cols-2 ">
		  			<div class="font-semibold mb-1 "> <%= lesson.name %> </div>
		    		<div class=" grid grid-cols-3 ">
							<%= link_to lesson_status(lesson.id) == "started" ? t('lesson.show.continue'): t('lesson.index.start') , lesson_path(id: lesson.id, less_id: lesson.id ) , class: " text-blue-400 block px-4 text-left mx-1 border border-2 border-blue-300  rounded-sm hover:bg-blue-100 ", style: "color: rgb(96, 165, 250);" %>
							<% if current_user && current_user.admin %>
		      			<%= link_to t('general_buttons.edit'), edit_lesson_path(lesson.id) , class: " text-green-400 border border-2 border-green-400 text-center block mx-1 hover:bg-green-100 hover:text-green-600" %>
								<%= link_to t('lesson.index.delete_lesson') , lesson_path(lesson.id)  ,method: :delete ,  class: " border border-4 border-red-400 border-red-400 block text-right  mx-1 px-4 hover:bg-red-200 ", style: "color: rgb(248, 113, 113);" %>
							<% end %>
						</div>
					</div>
					<div class=""> status: <span class="font-semibold text-blue-400 "><%= lesson_status(lesson.id) %></span> </div>
				<div class="flex">
					<div class="h-1 relative max-w-xl rounded-full w-full  overflow-hidden">
              <div class="w-full h-full bg-gray-200  absolute"></div>
              <div id="bar" class="h-full bg-<%= lesson_status_colour(lesson.id)%> relative text-gray-900" style="width: <%= lesson_completion_percent(lesson.id)%>%"> </div>
          </div>
					<div class="pl-4"> <%=lesson_completion_percent(lesson.id) %>% </div>
				</div>
				</div>
			<% end %>
		<% end %>
<br>
<% if current_user && current_user.admin %>
<%= link_to t('lesson.index.new_lesson') , new_lesson_path , class: "bg-green-600 text-white  font-semibold px-8 py-1 border border-1 border-green-600" , style: "color: #fff ;"%>
<% end %>
 </section>

app/views/lessons/new.html.erb
<section class="flex flex-col justify-center content-center ">
<h1 class =" text-center font-hairline mt-5 text-2xl"><%= t('lesson.new.new_lesson') %></h1>
        <div class="w-full text-lg px-5 pt-10 ">
                <div class=" ">
                        <%= render 'form', lesson: @lesson %>
                </div>
                <%= link_to t('general_buttons.back'), lessons_path %>
        </div>
</section>

app/views/lessons/show.html.erb
<%= javascript_pack_tag 'lesson' %>

<section class="w-full md:w-4/5 mt-5">
	<div class= "flex"> 
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 "> <%= link_to '<i class="fa fa-arrow-left fa-2x" aria-hidden="true"></i>'.html_safe, lessons_path, style: "color: #fff;" %> </div>
		<h1 class="text-xl w-full text-center border-2 border-gray-300 "><%= @lesson.name %></h1>
		<div class="rounded-1/2 h-8 w-7 bg-gray-900 text-white px-1 "> <%= link_to '<i class="fa fa-arrow-right fa-2x" aria-hidden="true"></i>'.html_safe, quiz_path, style: "color: #fff;" %> </div>
	</div>
	<div class="grid grid-cols-1 md:grid-cols-3">
		<div class="col-span-3 px-10 py-4">
			<p id="notice"><%= notice %></p>
			<% if current_user && current_user.admin && check_for_restart %>
			<div class= "grid grid-cols-3   py-4">
			<% else %>
			<div class= "  grid grid-cols-2 py-4">
			<% end %>
				<% if current_user && current_user.admin %> <%= link_to t('general_buttons.edit'), edit_lesson_path(@lesson), class: "font-semibold block px-8 py-1 border border-4 border-green-400 text-center hover:bg-green-200", style: "color: #22ab46;" %>   <% end %>
				<% if check_for_restart %>
	       <%= link_to t('lessons.show.restart'), quiz_restart_url , class: "block w-full border border-2 border-purple-400 text-center"%>    <% end %>
				<% if check_quiz.empty? %>
					<% if current_user.admin %>
						<%= link_to t('lessons.show.create_quiz'),new_quiz_path , class: "block bg-green-600 px-8 py-1 font-semibold " , style: "color: #fff;"%>
					<% else %>
						<div class=" "> <%= t('lessons.show.no_quizzes') %>  </div>
					<% end %>
				<% else %>
					<% if !finished_quizzes?(@lesson.id) %>
						<% if !check_for_restart %>
							<%= link_to t('lessons.show.next') , quiz_path() , class: "font-semibold  block px-8 py-1 text-right border border-4 border-blue-400 text-blue-400 hover:bg-blue-100 ", style: "color: #2116df;" %> 
						<%else%>
							<%= link_to t('lessons.show.continue') , quiz_path() , class: "font-semibold  block px-8 py-1 text-right border border-4 border-blue-400 text-blue-400 hover:bg-blue-100 ", style: "color: #2116df;" %> 
						<%end%>
					<%end%>	
				<% end %>
		</div>

		<div class="grid  md:grid-cols-1 "> 
			<div class="flex justify-between border border-2 border-gray-300 px-2 hover:bg-gray-100 vid_but ">
				<div class="font-semibold text-lg"><%= t('lessons.show.video') %></div>
				<div class="  pr-1 ">
					<svg class="-mr-1 ml-2 h-5 w-5 "  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
											<path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
					   						</svg>
				</div>

			</div>
						<div class=" w-full  vid_pane"> 
				<% if @lesson.lesson_video.attached? %>
				<%= video_tag(url_for(@lesson.lesson_video), style: "width: 100% ; height: auto; ", controls: "" ) %>  
				<% end %>
				</div>
				
				<div class="flex justify-between mt-10  border border-2 border-gray-300 px-2 note_but hover:bg-gray-100">
				<div class="font-semibold text-lg"><p class="font-bold text-lg "> <%= t('lessons.show.notes_on') + " : " + @lesson.name  %> </p></div>
				<div class="  pr-1 ">
					<svg class="-mr-1 ml-2 h-5 w-5 "  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
											<path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />

					   						</svg>
				</div>

			</div>
				
				<div class=" notes_pane">
					<p class=""> <%= @lesson.lesson_notes %> </p>
				</div>
				
				<div class="flex justify-between mt-10 border border-2 border-gray-300 px-2 hover:bg-gray-100 other_but">
				<div class="font-semibold text-lg"><p class="text-lg font-bold"> <%= t('lessons.show.other_material') %> :</p> </div>
				<div class="  pr-1 ">
					<svg class="-mr-1 ml-2 h-5 w-5 "  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
											<path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
					   						</svg>
				</div>
			</div>
			<br> <br>
			<div class="w-full my-4 text-left  pic_pane"> 
				<p class=" text-md font-semibold"> <%= t('lessons.show.images') %> : </p>
			
			<div class="w-full grid grid-cols-1 md: grid-cols-3"> 
				<% @lesson.lesson_pictures.each do |picture| %>	
				<div class="px-2"> <%= link_to image_tag(picture), picture, style: "width: 100% ; height: auto; " %></div>
				<% end %>
			</div>
			</div>
		</div>
	</div>
	<div> <% if current_user %>
    		<div id = "right-pane" class="hidden border border-1 border-gray-100 md:block"><%= render 'layouts/rightpane', data: @data%></div>
    	<% end %></div>
	</div>
</section>
	 <script>


</script>