config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", locale: /en|fr/ do

	  resources :quizzes
	  resources :lessons do 
			member do
		    delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
		end
	  end
	  resources :subjects
	  devise_for :users
	  get 'quiz/restart', to: 'quizzes#restart'
	  get 'static/welcome', to: 'static#welcome'
	  get 'users/about', to: 'static#about'
	  get '/about', to: 'static#about'
	  get '/chat', to: 'static#chat'
	  get '/achievements', to: 'static#achievements'
	  get '/home', to: 'static#welcome'
	  get 'static/info', to: 'static#info'
		get '/passed', to: 'analysis#passed'
		get '/dash', to: 'static#admin_dash'
		get '/failed', to: 'analysis#failed'
		get '/usermore', to: 'static#usermore'
		get '/dash/user', to: 'static#info'
	  get 'static/landing_page', to: 'static#landing_page'
	  root 'static#landing_page'
	default_url_options :host => "www.gmail.com"
	  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	end
end

app/views/layouts/_darkleftpane.html.erb
<div class=" flex flex-row md:grid md:grid-cols-1 bg-gray-800 text-white  rounded w-full text-center py-2 px-2">
	<% if current_user.is? :admin %>
		<a href=" <%= dash_path %>" title="Statistics"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-chart-bar fa-2x" aria-hidden ="true"></i></p> </a>
		<a href=" <%= new_subject_path %>" title="New subject"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-book fa-2x" aria-hidden="true"></i></p> </a>

	<% end %>
	<a href=" <%= home_path %>" title="Home"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-home fa-2x" aria-hidden="true"></i></p> </a>
	<a href=" <%= chat_path %>" title="Chat"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-comments fa-2x" aria-hidden="true" ></i> </p> </a>
	<a href=" <%= achievements_path %>" title="Achievements"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-trophy fa-2x" aria-hidden="true" ></i> </p> </a>
	<a href=" <%= about_path %>" title="About"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-question fa-2x" aria-hidden="true" ></i> </p> </a>
	<a href=" <%= chat_path %>" title="Social"> <p class="my-4 text-gray-50 mx-4 md:mx-0"> <i class="fa fa-hashtag fa-2x" aria-hidden="true" ></i> </p> </a>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-green-500 border-t border-gray-400 shadow">	
      <div class="container max-w-md text-green-800 mx-auto py-8 flex">

          <div class="flex w-full ">
            <div class="px-8">
		<h1 class="font-bold text-md text-gray-200 ">Social: </h1>
              <ul class="list-reset flex flex-row items-center text-sm pt-3">
                <li>
                <a class="inline-block  no-underline hover:text-gray-100 hover:text-underline py-1 pr-4" href="#">
                  <i class="fab fa-facebook text-2xl"></i>
                </a>
                </li>
                <li>
                <a class="inline-block no-underline hover:text-gray-100 hover:text-underline py-1 pr-4" href="#">
                  <i class="fab fa-twitter text-2xl"></i>
                </a>
                </li>
                <li>
                <a class="inline-block  no-underline hover:text-gray-100 hover:text-underline py-1 pr-4" href="#">
                  <i class="fab fa-instagram text-2xl"></i>
                </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </footer>

app/views/layouts/_leftpane.html.erb
<section class = " flex flex-col min-h-screen">
	<div>
		<div class = " flex pt-5">
	<% if current_user %>
		<a href="<%= root_path(locale: current_user.locale) %>" class="block w-10 h-10 md:w-20 md:h-20 rounded-full  bg-blue-400" style="">
			<div class="font-semibold text-4xl md:text-6xl text-white "> <%= current_user.user_initial %> </div>
		</a>
		<div class = " items-center pl-4 pt-2 ">
			<p class="font-semibold text-md"> <%= current_user.full_name %> </p>
			<p class="text-sm font-hairline"> <%= current_user.email %></p>
		</div>
	
	</div>
	<div class="mt-5">

		<% end %>
			<% if current_user.is? :admin %>
			<%= link_to t('leftpane.statistics') , dash_path, class: "border border-2 border-gray-800 px-8 py-2 block mx-2 mb-2  text-center uppercase bg-gray-800", style: "color: #ccc;" %>
		<% end %>
		<% if current_user && current_user.admin %> 
		<a href="<%= new_subject_path %>" ><div class="text-center hover:text-blue-400 text-sm border mx-2 border-2 font-semibold px-4 py-2 rounded-md text-blue-300 "> <%= t('leftpane.new_subject') %> </div></a>		<% end %>
	</div>
<div class="w-full text-md flex-grow items-center lg:w-auto  lg:block mt-2 lg:mt-0 z-20" >
		<% if current_user %>
				<ul class="flex flex-col  px-4 md:px-4">
					<li class="mr-6 my-2 md:my-0">
                        <a href="/home" id="home" class="block py-1 md:py-3 pl-1 align-middle no-underline hover:text-green-300  border-0 hover:border-b-2  hover:border-blue-400">
                            <i class="fas fa-home fa-fw mr-3 text-blue-400"></i><span class="pb-1 md:pb-0 "><%= t('leftpane.home') %></span>
                        </a>
                    </li>
					 <li class="mr-6 my-2 md:my-0">
                        <a href="/achievements" class="block py-1 md:py-3 pl-1 align-middle  no-underline hover:text-green-300   hover:border-pink-400">
                            <i class="fas fa-tasks fa-fw mr-3"></i><span class="pb-1 md:pb-0 "> <%= t('leftpane.achievements') %></span>
                        </a>
                    </li> 
                    <li class="mr-6 my-2 md:my-0">
                        <a href="/chat" class="block py-1 md:py-3 pl-1 align-middle no-underline hover:text-green-300 hover:border-purple-400">
                            <i class="fa fa-envelope fa-fw mr-3"></i><span class="pb-1 md:pb-0 "> <%= t('leftpane.chat') %>
                            </span>
                        </a>
                    </li>
                    <li class="mr-6 my-2 md:my-0">
                        <a href="/about" class="block py-1 md:py-3 pl-1 align-middle  no-underline hover:text-green-300   hover:border-red-400">
                            <i class="fa fa-question-circle fa-fw mr-3"></i><span class="pb-1 md:pb-0 "> <%= t('leftpane.about') %></span>
                        </a>
                    </li>
				</ul>
				
			<% end %>
				
			</div>
	</div>
	<div class="flex-grow"></div>
  
	<%= render "layouts/footer" %>		

</section>

app/views/layouts/_navbar.html.erb
<nav class="  md:px-0 text-green-500 font-hairline text-lg">
	<div class="flex justify-between bg-gray-900 ">
		<a href="/" ><div class = " ml-4 font-bold text-white text-2xl">Sawa Learn </div></a>
				<div class="relative px-4 py-1 md:pr-0 w-1/2 hidden md:block">
                    <input type="search" placeholder= <%= t('navbar.search') %> class="w-full transition border border-green-800 focus:outline-none focus:border-gray-600 rounded py-1 px-2 pl-10 appearance-none bg-gray-200 leading-normal">
                    <div class="absolute search-icon" style="top: 0.375rem;left: 1.75rem;">
                        <svg class="fill-current pointer-events-none w-4 h-4 mt-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
                        </svg>
                    </div>
                </div>
		<div class="relative text-green-800">
            <button id="userButton" class="flex items-center focus:outline-none mr-3">
              <img class="w-8 h-8 rounded-full mr-4" src="http://i.pravatar.cc/300" alt="Ava"> <span class="hidden md:inline-block"><%= !current_user ? "Account" : t('navbar.hi') + " " + current_user.name  %></span>
              <svg class="pl-2 h-2 fill-current " version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 129 129"><g><path d="m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z"/></g></svg>
              </button>
              <div id="userMenu" class="bg-green-900 text-sm rounded shadow-md mt-2 absolute mt-12 top-0 right-0 min-w-full overflow-auto z-30 invisible">
	<ul class="list-reset">
		<% if locale != :en %>
		<li><%= link_to t('navbar.english'), root_path(locale: :en) , class: "px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline" , style: "color: white; "%></li>
		<% else %>
    <li><%= link_to t('navbar.french'), root_path(locale: :fr) , class: "px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline" , style: "color: white;"%>	
    		<% end %>
                <% if !current_user %>
                <li> <%= link_to t('navbar.login'), new_user_session_path, class: "px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline" %> </li>
                <li><%= link_to t('navbar.sign_up') , new_user_registration_path , class: "px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline" , style: "color: white;"%></li>
                <% else %>
                <li> <%= link_to t('navbar.account_info'), static_info_url(id: current_user.id)  , class: "px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline" , style: "color: white;"%> </li>
                <li><a href="#" class="px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline">Notifications</a></li>
                <li><hr class="border-t mx-2 border-gray-400"></li>
                <li class="bg-white"> <%= link_to t('navbar.logout'), destroy_user_session_url , :method => "delete" , class: "px-4 py-2 block text-gray-100 hover:bg-gray-800 no-underline hover:no-underline" , style: "color: red;"%> </li>
                <% end %>
						  </ul>
					  </div>
          </div>
		</div>
	</div>
	
			
	<hr>
</nav>


  <script>
    /* this script handles navbar click events */
    var userMenuDiv = document.getElementById("userMenu");
	var userMenu = document.getElementById("userButton");	
	document.onclick = check;
	function check(e){
	  var target = (e && e.target) || (event && event.srcElement);
	  //User Menu
	  if (!checkParent(target, userMenuDiv)) {
		// click NOT on the menu
		if (checkParent(target, userMenu) ) {
		  // click on the link
		  if (userMenuDiv.classList.contains("invisible")) {
			userMenuDiv.classList.remove("invisible");
		  } else {userMenuDiv.classList.add("invisible");}
		} else {
		  // click both outside link and outside menu, hide menu
		  userMenuDiv.classList.add("invisible");
		}
	  }
	  

	  
	}

	function checkParent(t, elm) {
	  while(t.parentNode) {
		if( t == elm ) {return true;}
		t = t.parentNode;
	  }
	  return false;
	}

    
  </script>

app/views/layouts/_rightpane.html.erb
<section class = "pl-4  text-gray-900 h-full">

	<div>
		<h1 class="font-bold pt-2 text-md"> <%= t('welcome.activity_feed') %> </h1>
		<hr>
		<% if @activity == nil %>
			<p> <%= t('welcome.no_activity') %> </p>
			<p> <%= @data %> </p>
		<% else %>
			<% @activity.each do |activity| %>
				<div class=" my-2">
					<p class="font-semibold"> <%= activity.name %> </p>
					<p> <%= activity.description %> </p>
					<p> <%= activity.created_at %> </p>
				</div>
			<hr>
			<%end%>
		<% end %>
	</div>
	<div id="status_view" class ="">

	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"> <!--Replace with your tailwind.css once created-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>

     <%= javascript_pack_tag 'application' %>
  </head>

  <body>

		<%= render 'layouts/navbar' %>
	
	
	<div class=" flex md:hidden">		
			<div class="md:hidden ">
      			<p id="menu" class="block hover:bg-green-300  py-1 px-1 align-middle text-green-500 no-underline   border-blue-400 hover:border-green-400">
      				<svg viewBox="0 0 100 80" width="30" height="30">
        				<rect y="20" width="100" height="10"></rect>
        				<rect y="40" width="100" height="10"></rect>
        				<rect y="60" width="100" height="10"></rect>
        				<rect y="80" width="100" height="10"></rect>
      				</svg> </p>
      			</div>
		</div>	
	<% if !current_user %>
		<div class="">
	<% else %>
	<div class= " md:grid md:grid-cols-5 min-h-screen">
	<% end %>
	  <% if current_user %>
			<div id="left-pane" class=" hidden md:block border border-1  border-gray-100 bg-gray-900 text-white md:bg-white w-1/3 mt-4 ml-3"><%= render 'layouts/darkleftpane' %></div>	
		<% end %>
		<div class=" col-span-4 border border-1 border-gray-100 flex-grow"><%= yield %></div>

		  
    	</div>
    			<% if !current_user %>
					<div class =" "> <%= render 'layouts/footer' %> </div>
					<% end %>
	
  </body>
  

</html>

<script>
	$('#menu').click( function(){
			$('#left-pane').toggleClass("hidden");
			$('#left-pane').toggleClass("absolute");
			$('#left-pane').toggleClass("z-30");
		});
</script>

app/views/layouts/empty_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet"> <!--Replace with your tailwind.css once created-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.min.js" integrity="sha256-XF29CBwU1MWLaGEnsELogU6Y6rcc5nCkhhx89nFMIDQ=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
     <%= javascript_pack_tag 'application' %>
  </head>

  <body style="background-image: url('<%= image_url("school_girls.jpg") %>') ; width: auto; height: auto;">
	<div class= "">
		
		<div class="  border border-1 border-gray-100"><%= yield %></div>
    	</div>
	
  </body>
  

</html>